department_names = {
    5: 'Régions et Départements d\'outre-mer',
    11: 'Ile-de-France',
    24: 'Centre-Val de Loire',
    27: 'Bourgogne-Franche-Comté',
    28: 'Normandie',
    32: 'Hauts-de-France',
    44: 'Grand Est',
    52: 'Pays de la Loire',
    53: 'Bretagne',
    75: 'Nouvelle-Aquitaine',
    76: 'Occitanie',
    84: 'Auvergne-Rhône-Alpes',
    93: 'Provence-Alpes-Côte d\'Azur',
    0: 'Inconnu',
    99: 'Inconnu'
}

medication_categories = {
    'A': 'SYSTEME DIGESTIF ET METABOLISME',
    'B': 'SANG ET ORGANES HEMATOPOIETQUES',
    'C': 'SYSTEME CARDIO-VASCULAIRE',
    'D': 'DERMATOLOGIE',
    'G': 'SYSTEME GENITO-URINAIRE ET HORMONES SEXUELLES',
    'H': 'HORMONES SYSTEMIQUES, A L EXCLUSION DES HORMONES SEXUELLES ET DES INSULINES',
    'J': 'ANTI-INFECTIEUX (USAGE SYSTEMIQUE)',
    'M': 'SYSTEME MUSCULO-SQUELETTIQUE',
    'N': 'SYSTEME NERVEUX',
    'P': 'ANTIPARASITAIRES, INSECTICIDES ET REPULSIFS',
    'R': 'SYSTEME RESPIRATOIRE',
    'S': 'ORGANES SENSORIELS',
    'V': 'DIVERS'
}

psp_spe_labels = {
    1: "MEDECINE GENERALE LIBERALE",
    2: "ANESTHESIOLOGIE - REANIMATION LIBERALE",
    3: "PATHOLOGIE CARDIO-VASCULAIRE LIBERALE",
    4: "CHIRURGIE LIBERALE",
    5: "DERMATOLOGIE ET VENEROLOGIE LIBERALE",
    6: "RADIOLOGIE LIBERALE",
    7: "GYNECOLOGIE OBSTETRIQUE LIBERALE",
    8: "GASTRO-ENTEROLOGIE ET HEPATOLOGIE LIBERALE",
    9: "MEDECINE INTERNE LIBERALE",
    11: "OTO RHINO-LARYNGOLOGIE LIBERALE",
    12: "PEDIATRIE LIBERALE",
    13: "PNEUMOLOGIE LIBERALE",
    14: "RHUMATOLOGIE LIBERALE",
    15: "OPHTALMOLOGIE LIBERALE",
    17: "PSYCHIATRIE LIBERALE",
    18: "STOMATOLOGIE LIBERALE",
    19: "CHIRURGIE DENTAIRE",
    31: "MEDECINE PHYSIQUE ET DE READAPTATION LIBERALE",
    32: "NEUROLOGIE LIBERALE",
    35: "NEPHROLOGIE LIBERALE",
    36: "CHIRURGIE DENTAIRE (SPECIALISTE O.D.F.)",
    37: "ANATOMIE-CYTOLOGIE-PATHOLOGIQUE LIBERALE",
    38: "DIRECTEUR LABORATOIRE MEDECIN LIBERAL",
    42: "ENDOCRINOLOGIE ET METABOLISMES LIBERAL",
    90: "PRESCRIPTEURS SAALARIES",
    98: "PRESCRIPTEURS DE VILLE AUTRES QUE MEDECINS",
    99: "VALEUR INCONNUE"
}

category_mappings = {
    'A': 'SYSTEME DIGESTIF ET METABOLISME',
    'B': 'SANG ET ORGANES HEMATOPOIETQUES',
    'C': 'SYSTEME CARDIO-VASCULAIRE',
    'D': 'DERMATOLOGIE',
    'G': 'SYSTEME GENITO-URINAIRE ET HORMONES SEXUELLES'
}